### ISSUE TITLE
Placeholder-polyfill: Value bei submit gesetzt

### ISSUE THREAD

**Issue by GNi33** [Netural/Snippets#2]
Bei diesem Snippet hätten wir wohl das Problem, dass bei älteren Browsern ohne support ein nicht ausgefülltes "required" - Feld, welches nur auf Text-Inhalt überprüft wird, mit dem Value des placeholder-Attributs abgeschickt werden würde. 

Entweder muss das onSubmit noch überprüft werden, oder man tendiert eher zur Verwendung von etwas wie [diesem Plugin](https://github.com/mathiasbynens/jquery-placeholder/)

**Comment by thomaspink** [comment]
no longer needed ;)
